"""
Email draft generator for weekly client updates.

Uses Claude-generated insights to produce professional,
client-facing email content.
"""

import structlog
from typing import Any, Dict

logger = structlog.get_logger(__name__)


class EmailGenerator:
    """Generates email drafts for weekly client updates."""

    async def generate_weekly_email(
        self,
        data: Dict[str, Any],
        insights: Dict[str, Any],
        week_of: str,
    ) -> Dict[str, str]:
        """Generate a weekly update email draft.

        Returns {"subject": ..., "body_html": ..., "body_text": ...}
        """
        subject = insights.get("email_subject", f"Schumacher Homes — Weekly Performance Update ({week_of})")
        body_text = insights.get("email_body", self._fallback_body(data, week_of))

        # Convert text to basic HTML
        paragraphs = body_text.split("\n\n")
        body_html = "".join(f"<p>{p.strip()}</p>" for p in paragraphs if p.strip())

        # Wrap in a styled container
        body_html = f"""
<div style="font-family: Arial, sans-serif; max-width: 600px; color: #333; line-height: 1.6;">
    {body_html}
    <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;" />
    <p style="color: #999; font-size: 12px;">
        Generated by Schumacher Ads Dashboard
    </p>
</div>
"""

        return {
            "subject": subject,
            "body_html": body_html.strip(),
            "body_text": body_text,
        }

    def _fallback_body(self, data: Dict[str, Any], week_of: str) -> str:
        """Generate a basic email body when AI insights are unavailable."""
        agg = data.get("aggregated", {})
        spend = agg.get("total_spend", 0)
        leads = agg.get("total_leads", 0)
        cpl = agg.get("blended_cpl", 0)

        return f"""Hi Team,

Here is this week's performance update for Schumacher Homes paid media campaigns (week of {week_of}).

This week we spent ${spend:,.0f} across all platforms, generating {leads:,} leads at a blended cost per lead of ${cpl:,.2f}.

We'll continue monitoring performance and making optimizations. Please let us know if you have any questions.

Best regards"""
